//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuolingoSk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Exam
    {
        public long Exam_Id { get; set; }
        public Nullable<long> StudentId { get; set; }
        public Nullable<System.DateTime> ExamDate { get; set; }
        public Nullable<long> AgentId { get; set; }
        public string Score { get; set; }
        public string ResultText { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<long> QuestionLevelId { get; set; }
        public Nullable<int> ResultStatus { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
