//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuolingoSk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_QuestionsMaster
    {
        public long QuestionId { get; set; }
        public string QuestionText { get; set; }
        public Nullable<int> QuestionTime { get; set; }
        public Nullable<int> QuestionTypeId { get; set; }
        public string QuestionOptionText { get; set; }
        public string Words { get; set; }
        public string Mp3FileName { get; set; }
        public string Mp3FileText { get; set; }
        public Nullable<int> MaxReplay { get; set; }
        public string ImageName { get; set; }
        public Nullable<int> NoOfWords { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
