//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuolingoSk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Webinar
    {
        public int WebinarId { get; set; }
        public int PackageId { get; set; }
        public string WebinarMessage { get; set; }
        public Nullable<int> TotalAttendedStudent { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public long CreatedBy { get; set; }
    }
}
