//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuolingoSk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_StudentWebinar
    {
        public long StudentWebinarId { get; set; }
        public int WebinarId { get; set; }
        public long StudentId { get; set; }
        public long StudentFeeId { get; set; }
        public long PackageId { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
