//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuolingoSk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Feedback
    {
        public long PK_FeedBack_Id { get; set; }
        public string FeedbackQuestion { get; set; }
        public string FeedbackAnswer { get; set; }
        public Nullable<long> ExamId { get; set; }
        public Nullable<long> StudentId { get; set; }
        public Nullable<System.DateTime> FeedBackDate { get; set; }
    }
}
